### ISSUE TITLE
Errors when "Context checking DNS LDAP SRV records"

### ISSUE THREAD

**Issue by alexaymonier** [markwragg/Test-ActiveDirectory#3]
Hi Mark,

Just staring out with Pester and ran across these AD tests. All is wokring as it should except for the "Context checking DNS LDAP SRV records" part.

I've copied what the tests are doing and i can replicate the errors in relation to the order that the results come back in. 

$object is the clixml import from the "ADGoldConfig-2018-04-09.xml" file.
$ADSnapshot is from the test file "$ADSnapshot = Invoke-Expression ".\Get-ADConfig.ps1 -ExportToXML:$False""

```
PS C:\Users\alex.aymonier\Downloads\Test-ActiveDirectory-master> $object.ldapdns

Name                                     Type   TTL   Section    NameTarget                     Priority Weight Port
----                                     ----   ---   -------    ----------                     -------- ------ ----
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc01.ugnsw.local       0        100    389
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc02.ugnsw.local       0        100    389
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc03.ugnsw.local       0        100    389
```
```
PS C:\Users\alex.aymonier.adm\Downloads\Test-ActiveDirectory-master> $ADSnapshot.ldapdns

Name                                     Type   TTL   Section    NameTarget                     Priority Weight Port
----                                     ----   ---   -------    ----------                     -------- ------ ----
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc03.ugnsw.local       0        100    389
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc01.ugnsw.local       0        100    389
_ldap._tcp.domain.LOCAL                   SRV    600   Answer     dc02.ugnsw.local       0        100    389
```
I've tested this in a couple of environments and get the same result every time.

Thanks,
Alex

**Comment by luzkenin** [comment]
I ran into this issue to and I solved it by sorting by name and type:
`    Context 'checking DNS LDAP SRV records'{
	$LDAPDNS = $ADSnapshot.LDAPDNS | sort name,type
        $i = 0
        foreach ($entry in $ADGoldConfig.LDAPDNS | sort name, type){
                it "LDAP result entry $i`: $($entry.Name)" {
                    $entry.Name | Should be ($LDAPDNS[$i]).Name`

**Comment by markwragg** [comment]
I've added a `sort` to both the cmdlet that gathers the initial config and the test. Thanks for raising the issue, sorry it took me a while to get round to dealing with.
